import { BookOpen, Bell, Bookmark, Moon, Type } from "lucide-react";
import { SiteFooter, SiteHeader } from "../../site-chrome";
export const metadata={title:"Versículo do Dia & Bíblia — Larzus Apps",description:"Uma experiência simples e acolhedora para leitura bíblica, reflexão e inspiração diária."};
export default function AppPage(){return <><SiteHeader/><main className="app-detail shell"><section className="app-detail-hero"><div><span className="kicker">ESTILO DE VIDA · ESPIRITUALIDADE</span><h1>Versículo do Dia<br/>&amp; Bíblia</h1><p>Uma experiência simples e acolhedora para leitura bíblica, reflexão e inspiração diária.</p><span className="status"><i/>Em desenvolvimento</span><div className="store-links"><span className="disabled-store">Google Play · em breve</span><span className="disabled-store">App Store · em breve</span></div></div><div className="app-detail-icon"><div><BookOpen size={70}/></div></div></section>
<span className="kicker">PRÉVIAS DO APLICATIVO</span><h2>Telas pensadas para uma leitura tranquila.</h2><div className="screens"><div className="screen"><span>LEITURA DIÁRIA</span><h3>Uma palavra para acompanhar o seu dia.</h3></div><div className="screen"><span>BÍBLIA</span><h3>Encontre e continue sua leitura com clareza.</h3></div><div className="screen"><span>SALVOS</span><h3>Guarde passagens para revisitar quando quiser.</h3></div></div>
<span className="kicker">RECURSOS PLANEJADOS</span><h2>O essencial, bem resolvido.</h2><div className="feature-list"><Feature icon={BookOpen} title="Leitura bíblica" text="Navegação clara para uma experiência de leitura confortável."/><Feature icon={Bell} title="Versículo diário" text="Conteúdo diário apresentado de forma simples e acolhedora."/><Feature icon={Bookmark} title="Itens salvos" text="Um espaço para guardar passagens importantes."/><Feature icon={Type} title="Leitura confortável" text="Controles pensados para diferentes preferências de leitura."/><Feature icon={Moon} title="Modo noturno" text="Uma aparência mais confortável para ambientes com pouca luz."/></div>
<span className="kicker">PERGUNTAS FREQUENTES</span><h2>Sem mistério.</h2><div className="faq-list"><Faq q="Quando o aplicativo será lançado?" a="O produto ainda está em desenvolvimento. A data será informada nos canais oficiais da Larzus Apps."/><Faq q="Em quais plataformas estará disponível?" a="A previsão é oferecer versões para Android e iOS. Os links oficiais aparecerão nesta página quando estiverem disponíveis."/><Faq q="O aplicativo será gratuito?" a="O modelo de disponibilidade ainda não foi anunciado."/><Faq q="Como falar com o suporte?" a="Use o canal de suporte indicado abaixo. Antes da publicação, substitua o endereço provisório pelo e-mail oficial."/></div>
<div className="support-box"><div><h2>Precisa de ajuda?</h2><p>O canal oficial de suporte será informado antes do lançamento.</p></div><span className="button">[suporte@larzusapps.com]</span></div></main><SiteFooter/></>}
function Feature({icon:Icon,title,text}:{icon:typeof BookOpen,title:string,text:string}){return <article><Icon size={22}/><h3>{title}</h3><p>{text}</p></article>}
function Faq({q,a}:{q:string,a:string}){return <details><summary>{q}</summary><p>{a}</p></details>}
