import Link from "next/link";
import { ArrowRight, BookOpen, Check, Code2, Eye, Layers3, LockKeyhole, Mail, MessageCircle, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import { SiteFooter, SiteHeader } from "./site-chrome";
const principles=[{icon:Layers3,title:"Simplicidade",text:"Menos distração. Mais clareza para fazer o que importa."},{icon:Eye,title:"Experiência",text:"Cada detalhe pensado para parecer natural desde o primeiro uso."},{icon:LockKeyhole,title:"Privacidade",text:"Respeito aos dados não é extra. É ponto de partida."},{icon:Check,title:"Qualidade",text:"Produtos bem cuidados, do conceito à última tela."},{icon:RefreshCw,title:"Evolução",text:"Ouvir, aprender e melhorar continuamente — sem complicar."}];
function HeroVisual(){return <div className="hero-visual" aria-label="Prévia conceitual de interfaces da Larzus Apps"><div className="soft-orbit orbit-one"/><div className="soft-orbit orbit-two"/><div className="phone phone-back"><div className="phone-top"/><div className="mini-label">HOJE</div><div className="verse-lines"><i/><i/><i/></div><div className="tiny-row"><span/><span/><span/></div></div><div className="phone phone-front"><div className="phone-top"/><div className="app-mark"><BookOpen size={25}/></div><div className="mini-label">VERSÍCULO DO DIA</div><div className="verse-copy">“Uma pausa para ler, refletir e seguir.”</div><div className="reference">Leitura diária</div><button tabIndex={-1}>Abrir leitura <ArrowRight size={14}/></button></div><div className="floating-card float-top"><Sparkles size={17}/><span><b>Feito com cuidado</b><small>Do primeiro toque ao último detalhe</small></span></div><div className="floating-card float-bottom"><ShieldCheck size={18}/><span><b>Privacidade primeiro</b><small>Simples também nos bastidores</small></span></div></div>}
export default function Home(){return <><SiteHeader/><main>
<section className="hero shell" id="inicio"><div className="hero-copy"><div className="eyebrow"><span/>Produtos digitais feitos com intenção</div><h1>Apps úteis.<br/><em>Simples de verdade.</em></h1><p>Somos um estúdio independente que transforma boas ideias em produtos digitais bonitos, acessíveis e fáceis de usar.</p><div className="actions"><a className="button primary" href="#apps">Conheça nossos apps <ArrowRight size={17}/></a><a className="button secondary" href="#sobre">Sobre a Larzus</a></div><div className="micro-proof"><span className="avatar-mark">L</span><span>Um pequeno estúdio.<br/><b>Um cuidado enorme.</b></span></div></div><HeroVisual/></section>
<section className="section shell" id="apps"><div className="section-heading"><div><span className="kicker">NOSSO PORTFÓLIO</span><h2>Produtos que fazem<br/>sentido no dia a dia.</h2></div><p>Começamos com um app, mas a casa foi feita para muitos. Aqui você encontrará cada novo produto da Larzus.</p></div><div className="apps-grid"><article className="app-card featured"><div className="app-card-top"><div className="product-icon peach"><BookOpen size={30}/></div><span className="status"><i/>Em desenvolvimento</span></div><span className="category">ESTILO DE VIDA · ESPIRITUALIDADE</span><h3>Versículo do Dia &amp; Bíblia</h3><p>Uma experiência simples e acolhedora para leitura bíblica, reflexão e inspiração diária.</p><div className="card-footer"><div className="platforms"><span>Android</span><span>iOS</span></div><Link href="/apps/versiculo-do-dia" className="text-link">Conhecer <ArrowRight size={16}/></Link></div></article><Future tone="blue" icon={Code2} label="PRÓXIMOS PRODUTOS" title="Novas ideias a caminho" text="Ferramentas web, aplicativos e serviços digitais poderão morar aqui." foot="EM BREVE"/><Future tone="lavender" icon={Sparkles} label="ESPAÇO EM ABERTO" title="O próximo pode ser diferente" text="Nossa identidade cresce com o produto — sem ficar presa a uma categoria." foot="FUTURO PRODUTO"/></div></section>
<section className="about-wrap" id="sobre"><div className="about shell"><div className="about-art"><div className="studio-tile"><span className="big-l">L</span><small>LARZUS<br/>APPS</small></div><div className="detail-card"><span>01</span><p>Útil antes de tudo.<br/>Bonito porque importa.</p></div></div><div className="about-copy"><span className="kicker">SOBRE A LARZUS</span><h2>Pequenos no tamanho.<br/>Grandes no cuidado.</h2><p>A Larzus Apps é um estúdio independente de aplicativos e produtos digitais. Criamos soluções que respeitam o tempo das pessoas: úteis, simples, bonitas e acessíveis.</p><p>Trabalhamos perto de cada ideia, cuidando da experiência inteira — do primeiro rascunho ao produto que chega às mãos de quem usa.</p><div className="signature"><span>L</span><div><b>Larzus Apps</b><small>Estúdio independente de produtos digitais</small></div></div></div></div></section>
<section className="section shell" id="principios"><div className="section-heading centered"><div><span className="kicker">COMO PENSAMOS</span><h2>Princípios simples.<br/>Produtos melhores.</h2></div><p>São as escolhas que fazemos quando ninguém está olhando que definem o que colocamos no mundo.</p></div><div className="principles-grid">{principles.map(({icon:Icon,title,text},i)=><article key={title} className={`principle p${i+1}`}><span className="number">0{i+1}</span><Icon size={23}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="contact-wrap" id="contato"><div className="contact shell"><div><span className="kicker">VAMOS CONVERSAR</span><h2>Uma boa conversa<br/>pode ser o começo.</h2><p>Dúvidas ou precisa de ajuda? Escolha o canal mais adequado.</p></div><div className="contact-grid"><Contact icon={Mail} title="Contato geral" value="contato@larzusapps.com"/><Contact icon={MessageCircle} title="Suporte" value="suporte@larzusapps.com"/></div></div></section>
</main><SiteFooter/></>}
function Contact({icon:Icon,title,value}:{icon:typeof Mail,title:string,value:string}){return <a className="contact-item" href={`mailto:${value}`}><span><Icon size={19}/></span><span className="contact-copy"><b>{title}</b><small>{value}</small></span></a>}
function Future({tone,icon:Icon,label,title,text,foot}:{tone:string,icon:typeof Code2,label:string,title:string,text:string,foot:string}){return <article className={`app-card future ${tone}`}><div className="product-icon"><Icon size={27}/></div><div><span className="category">{label}</span><h3>{title}</h3><p>{text}</p></div><span className="quiet-label">{foot}</span></article>}
